### PR TITLE
Ensure reducer called after commit/revert

### PR DESCRIPTION
**Pull request by mwalsher**
I added failing test cases (3348432) and a fix (64d6d9a) for #5. Let me know if all looks good!

### CODE REVIEW

**Comment by mattkrick** [comment]
OK, so the success/error isn't an action itself, it's just part of the action.meta & then based on that you can do whatever you want in the middleware. Check out meatier to see an example, it does exactly what you wanna do.

**Comment by mwalsher** [comment]
I checked out meatier and I am trying to more or less do the same thing as what you're doing with regard to setting the error state in optimisticMiddleware:

```
socket.emit('graphql', payload, error => {
  next({
    type: type + (error ? _ERROR : _SUCCESS),
    error,
    payload,
    meta: {
      synced: true,
      optimistic: error ? {type: REVERT, id: transactionID} : {type: COMMIT, id: transactionID}
    }
  });
});
```

Unless I'm mistaken, the same problem exists in meatier when a socket error occurs – the reducer for the ``${type}_ERROR`` action is not being called and thus the error state is never set. For example, if I kill rethinkdb and try adding a note to a lane, this code never executes:

```
case ADD_NOTE_ERROR:
case UPDATE_NOTE_ERROR:
case DELETE_NOTE_ERROR:
  debugger
  return state.merge({
    synced: true,
    error: action.error || 'Error'
  });
```

**Comment by mattkrick** [comment]
The error handling should live as close to the error source as possible, in this case the server. For example, if the DB fails, the graphQL resolve function will fail, which means the graphQL call will return an error. See https://github.com/mattkrick/meatier/blob/master/src/server/graphql/wsGraphQLHandlers.js#L19
That ensures the durable messaging will always return a callback, unless the server dies. But if the server dies, the client doesn't know that, so it should probably treat it as just a long running process.

**Comment by mwalsher** [comment]
Okay sure, that makes sense. But regardless, why would you not want an action dispatched with the REVERT/COMMIT meta parameter to make its way to the reducer? I can't think of any drawback in doing so and would say it is the expected behaviour. 

I also can't think of an instance where you'd want to REVERT the state and _not_ have the reducer set some sort of error state. The same goes for a COMMIT... how would you sync your state if the action doesn't make it to the reducer?

Again, using meatier's optimisticMiddleware example where you dispatch the REVERT/COMMIT:

```
next({
  type: type + (error ? _ERROR : _SUCCESS),
  error,
  payload,
  meta: {
    synced: true,
    optimistic: error ? {type: REVERT, id: transactionID} : {type: COMMIT, id: transactionID}
  }
});
```

You would have to dispatch the action twice (once with the REVERT/COMMIT and once without) for the type_ERROR or type_SUCCESS action to make its way to the reducer, which is pretty clunky.

**Comment by mattkrick** [comment]
It's all about forcing best practices. In redux land, an async has a
request, success, and fail action associated with it. The request goes out,
you make an isFetching boolean true or whatever, then on success or fail,
you add an error or response to your state and turn the isFetching back to
false. Doing so keeps that jackwagon on your team from going rogue.

**Comment by mwalsher** [comment]
Maybe I'm not explaining the issue very well, but that's exactly what I'm trying to do here. Again, the bug can be seen in meatier as well. Your ADD_NOTE_SUCCESS and ADD_NOTE_ERROR reducers are never called. If you stick a console.log or debugger in either you can see for yourself.

**Comment by mattkrick** [comment]
Sorry for the late response, success & error reducers are definitely called in meatier, otherwise CRUD actions wouldn't be possible, (plus it'd be a huuuuuge memory leak that this package would eventually catch). Have you tried starting with a fresh clone?

**Comment by mwalsher** [comment]
I just tried again with a fresh clone and can 100% confirm that your `ADD_NOTE_SUCCESS` and `ADD_NOTE_ERROR` reducers are not being called. `ADD_NOTE` is, which optimistically updates the state, but `ADD_NOTE_SUCCESS` is not.

This is a direct result of the bug reported in this issue - which again is confirmed by the failing test cases in my PR.

You can reproduce this yourself by adding a `console.log` or `debugger` to line 69 of src/universal/modules/kanban/ducks/notes.js. Then try adding a note and you will see that line is never executed.

**Comment by mattkrick** [comment]
@mwalsher ohhhhhh dang, you're right i'm wrong, THANK YOU for keeping with this & getting me to see what you're talking about. Unfortunately, the fix is a little more involved because we'll need to add the COMMIT/REVERT actions to the history so they can be replayed. I've got a new version working, just need to write some more tests, will publish tomorrow.

**Comment by mwalsher** [comment]
:+1: :+1: no problem

**Comment by mattkrick** [comment]
0.4.0 incorporates all the changes. the 2nd to last test shows that, although probably not practical, the resolve action (commit/revert) could modify the exact part of the state the the async action does.

**Pull request closed without merging**
