### PR TITLE
fix: support nested combineReducers

### PR DESCRIPTION
**Pull request by maxlapides**

### CODE REVIEW

**Comment by rossman15** [comment]
I was having the same problem! This is a great fix!

**Comment by mattkrick** [comment]
LGTM, mind adding a test to make sure we don't have any regressions in future releases?

**Comment by maxlapides** [comment]
Okay, I wrote some unit tests...only to discover that they prove that my fix doesn't fix the problem 100%. I'll take another look and see if I can find a nice fix.

**Comment by maxlapides** [comment]
@mattkrick I think @rossman15 and I have a fix, and some tests to back it up! Can you please take a look and let us know what you think?

**Comment by mattkrick** [comment]
huh, neat fix, i don't quite understand it. why did removing the `id` cause it to error?

this LGTM. mind excluding the .editorconfig?

**Comment by maxlapides** [comment]
Okay, I removed .editorconfig.

Removing the `id` caused it to error because the same redux action needs to be used at multiple levels of the reducer "tree"

**Comment by maxlapides** [comment]
@mattkrick do you think you'll get a chance to look at this soon? :)

**Pull request merged**
